// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGP1q0JqjtSH8TmYDDOH_1O_T_EPfh6Ns',
    appId: '1:760347742156:web:ca4073b87cc5e5e3725769',
    messagingSenderId: '760347742156',
    projectId: 'pos-app-for-service-robot',
    authDomain: 'pos-app-for-service-robot.firebaseapp.com',
    databaseURL: 'https://pos-app-for-service-robot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pos-app-for-service-robot.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6ODz3MdWkv_F_5i9t3aS2FTMx8Ew1J0s',
    appId: '1:760347742156:android:af03f0a3704746d4725769',
    messagingSenderId: '760347742156',
    projectId: 'pos-app-for-service-robot',
    databaseURL: 'https://pos-app-for-service-robot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pos-app-for-service-robot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMt5X9q3e2i7fEYP2oU3WTVK0_Woec7Pk',
    appId: '1:760347742156:ios:cab3042590791189725769',
    messagingSenderId: '760347742156',
    projectId: 'pos-app-for-service-robot',
    databaseURL: 'https://pos-app-for-service-robot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pos-app-for-service-robot.appspot.com',
    iosClientId: '760347742156-d0r7e57ftgins111js90pl4tuka9hsdk.apps.googleusercontent.com',
    iosBundleId: 'com.example.posApplicationForServiceRobot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMt5X9q3e2i7fEYP2oU3WTVK0_Woec7Pk',
    appId: '1:760347742156:ios:cab3042590791189725769',
    messagingSenderId: '760347742156',
    projectId: 'pos-app-for-service-robot',
    databaseURL: 'https://pos-app-for-service-robot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pos-app-for-service-robot.appspot.com',
    iosClientId: '760347742156-d0r7e57ftgins111js90pl4tuka9hsdk.apps.googleusercontent.com',
    iosBundleId: 'com.example.posApplicationForServiceRobot',
  );
}
